from __future__ import annotations
import json
from pathlib import Path


def slug(v):
    return ''.join(ch if ch.isalnum() else '-' for ch in v.lower()).strip('-')


def render_scaffold(spec, out: Path):
    out.mkdir(parents=True, exist_ok=True)
    (out/'docs').mkdir(exist_ok=True)
    (out/'tests').mkdir(exist_ok=True)
    (out/'src').mkdir(exist_ok=True)
    (out/'README.md').write_text(f"# {spec['target']['name']}\n\nGenerated by Software_Factory v0.1.0 as an architecture-first starter.\n", encoding='utf-8')
    (out/'docs'/'SPECIFICATION.json').write_text(json.dumps({k:v for k,v in spec.items() if k!='_meta'}, indent=2, ensure_ascii=False), encoding='utf-8')
    (out/'docs'/'ARCHITECTURE.md').write_text('# Architecture\n\nSee generated factory evidence and architecture plan.\n', encoding='utf-8')
    (out/'src'/'README.md').write_text('# Implementation boundary\n\nDomain implementation belongs here.\n', encoding='utf-8')
    (out/'tests'/'test_generated.py').write_text('def test_generated_placeholder():\n    assert True\n', encoding='utf-8')
    return out
